name: First Workflow

on: push

jobs:
  my_first_job:
    name: "First Job"
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v4
      - name: Step 2
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Step 3
        run: python --version
